plugins:
  - uses:
      - plugin: "https://ubiquity-os-command-start-stop-main.ubiquity.workers.dev"
        skipBotEvents: false
        with:
          maxConcurrentTasks:
            collaborator: 999999
            contributor: 999999
  - uses:
      - plugin: "https://ubiquity-os-plugin-demo-main.ubiquity.workers.dev"
  - uses:
      - plugin: "https://ubiquity-os-command-wallet-main.ubiquity.workers.dev"
  - uses:
      - plugin: "ubiquity-os-marketplace/command-ask@main"
        with:
          model: "anthropic/claude-3.5-sonnet"
          openAiBaseUrl: "https://openrouter.ai/api/v1"
  - uses:
      - plugin: "https://ubiquity-os-command-query-user-main.ubiquity.workers.dev"
  - uses:
      - plugin: "ubiquity-os-marketplace/text-conversation-rewards@demo"
        skipBotEvents: false
        with:
          incentives:
            collaboratorOnlyPaymentInvocation: false
            contentEvaluator: {}
            userExtractor: {}
            dataPurge: {}
            formattingEvaluator: {}
            permitGeneration: {}
            githubComment: {}
          evmPrivateEncrypted: "E3T6IVvckcQfMEibaDyqdZ3TENaG1qArJXa9mgI-LmRPmBXzLOO9-kpBf4PBrcer9s9mt0saaEm3Vj2ffAUtPfEBaHsgkd6Lm9HlE1X_iMWHdkX8TUfcyMQX7mA6mp5lGXGOvyBFpxuic-3Rk7nM_vy3BO42t8ALq9ruat5fgMx2_i9x"
          erc20RewardToken: "0xC6ed4f520f6A4e4DC27273509239b7F8A68d2068"
          evmNetworkId: 100
  - uses:
      - plugin: "ubiquity-os-marketplace/daemon-disqualifier@main"
  - uses:
      - plugin: "https://ubiquity-os-comment-vector-embeddings-main.ubiquity.workers.dev"
